<testsuite name="Mocha Tests" tests="4" failures="1" errors="1" skipped="1" timestamp="2016-05-25T17:54:36" time="0.027">
<testcase classname="stest1 #sfoo1" name="Should run successfully" time="0"/>
<testcase classname="stest1 #sfoo1" name="Should run unsuccessfully" time="0"><failure message="test"><![CDATA[Error: test
    at Context.&lt;anonymous&gt; (D:\My Documents D\Stulsoft\mocha-jenkins\test\data\single_tests\stest1.js:11:18)
    at callFnAsync (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runnable.js:338:8)
    at Test.Runnable.run (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runnable.js:290:7)
    at Runner.runTest (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:422:10)
    at D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:533:12
    at next (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:342:14)
    at D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:352:7
    at next (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:284:14)
    at Immediate._onImmediate (D:\My Documents D\Stulsoft\mocha-jenkins\node_modules\mocha\lib\runner.js:320:5)]]></failure></testcase>
<testcase classname="stest2 #sfoo2" name="Should run successfully" time="0"/>
<testcase classname="test1 #foo" name="Should run successfully"><skipped/></testcase>
</testsuite>
